"""Scripted end-to-end demo, matching the 6-step MVP scenario:

  1. Before  — one attendee gets a personalised leave-time/gate plan
  2. Disruption — an MRT line goes down, the agent re-plans
  3. Crowd prediction — a gate gets congested, the agent re-routes
  4. Concert ends — simulate the exodus surge
  5. Decentralised distribution — 50,000-attendee-scale redistribution
  6. Journey Guardian — milestone messages through the whole journey

Run with:  python -m kallangflow.demo
Needs AWS Bedrock credentials set (see .env.example). Phases 1-5's non-LLM parts
(simulator + population + redistribution) still run and print without
a key — only the agent's own reasoning/recommendation calls need it.

The demo attendee's profile (home location, transport preference, etc.)
is now asked for interactively and saved to a local SQLite database
(attendees.db, via kallangflow/db.py) — the same database the Flask
app (app.py) reads from, so a profile set up in one place is visible
in the other.
"""
from __future__ import annotations

import os

from dotenv import load_dotenv

from .db import get_attendee, init_db, save_attendee
from .models import Attendee
from .population import (
    aggregate_signals,
    generate_population,
    redistribute_simulated,
    without_intervention_baseline,
)
from .simulator import advance_time, create_world_state, inject_disruption, simulate_crowd_buildup
from .tools import GUARDIAN_LOG

load_dotenv()

HAVE_KEY = bool(os.environ.get("AWS_ACCESS_KEY_ID")) and bool(os.environ.get("BEDROCK_MODEL"))

DEMO_ATTENDEE_ID = "A-DEMO"

# Event milestones — keep these in sync with app.py's EVENT_START_MINUTES /
# EVENT_END_MINUTES so the CLI demo and the web app simulate the same event.
EVENT_START_MINUTES = 19 * 60       # 19:00
EVENT_END_MINUTES = 22 * 60         # 22:00


def header(title: str) -> None:
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def bar_chart(counts: dict[str, int], total_label: str) -> None:
    max_val = max(counts.values()) if counts else 1
    for name, val in sorted(counts.items(), key=lambda kv: -kv[1]):
        bar_len = int(40 * val / max_val) if max_val else 0
        print(f"  {name:<20} {'#' * bar_len} {val}")
    print(f"  {'TOTAL':<20} {'':<40} {sum(counts.values())}  [{total_label}]")


def get_demo_attendee() -> Attendee:
    """Ask the user for their journey profile, or reuse a saved one if
    it already exists. Called once at the start of run_demo()."""
    init_db()
    existing = get_attendee(DEMO_ATTENDEE_ID)

    if existing is not None:
        print(f"\nFound a saved profile: home={existing.home_location}, "
              f"prefers {existing.transport_preference} transport"
              + (f", needs {existing.accessibility_needs}" if existing.accessibility_needs else "")
              + (f", travelling with {existing.travelling_with}" if existing.travelling_with else "") + ".")
        reuse = input("Reuse this profile? [Y/n] ").strip().lower()
        if reuse in ("", "y", "yes"):
            return existing
        print("Okay, let's set up a new profile.")

    print("\nLet's set up your journey profile.")
    home_location = input("Home location (e.g. Tampines): ").strip() or "Tampines"

    transport_preference = ""
    while transport_preference not in ("mrt", "bus", "taxi", "any"):
        transport_preference = input("Preferred transport [mrt/bus/taxi/any] (default mrt): ").strip().lower()
        if transport_preference == "":
            transport_preference = "mrt"

    accessibility_needs = input("Any accessibility needs? (leave blank if none): ").strip() or None
    travelling_with = input("Travelling with anyone needing extra care? (leave blank if none): ").strip() or None

    attendee = Attendee(
        id=DEMO_ATTENDEE_ID,
        home_location=home_location,
        transport_preference=transport_preference,
        accessibility_needs=accessibility_needs,
        travelling_with=travelling_with,
    )
    save_attendee(attendee)
    print("Profile saved — future runs will offer to reuse it.")
    return attendee


def run_demo() -> None:
    print("KallangFlow — simulated MVP demo. All transport/crowd data below")
    print("is SYNTHETIC, generated by kallangflow.simulator, not a live feed.")

    world = create_world_state(
        event_start_minutes=EVENT_START_MINUTES,
        event_end_minutes=EVENT_END_MINUTES,
    )
    demo_attendee = get_demo_attendee()

    # ---------------------------------------------------------- STEP 1
    header("STEP 1 — BEFORE: plan the journey")
    simulate_crowd_buildup(world)
    if HAVE_KEY:
        from .agent import run_agent_for_attendee
        result = run_agent_for_attendee(demo_attendee, world, milestone="before")
        print("Recommendation:", result["recommendation"])
    else:
        print("[AWS Bedrock credentials not set — skipping live agent call. "
              "Set them in .env to see the real recommendation here.]")

    # ---------------------------------------------------------- STEP 2
    header("STEP 2 — DISRUPTION: an MRT line goes down")
    inject_disruption(world, "stadium_mrt", note="signal fault, service suspended")
    print("Injected disruption:", world.disruptions[-1])
    if HAVE_KEY:
        result = run_agent_for_attendee(demo_attendee, world, milestone="before")
        print("Updated recommendation:", result["recommendation"])
    else:
        print("[Skipping live agent call — no API key.]")

    # ---------------------------------------------------------- STEP 3
    header("STEP 3 — CROWD PREDICTION: a gate gets congested")
    world.gates["gate_3"].load = int(world.gates["gate_3"].capacity * 0.9)
    print(f"Gate 3 congestion is now: {world.gates['gate_3'].congestion().value}")
    if HAVE_KEY:
        result = run_agent_for_attendee(demo_attendee, world, milestone="gate")
        print("Updated recommendation:", result["recommendation"])
    else:
        print("[Skipping live agent call — no API key.]")

    # ---------------------------------------------------------- STEP 4
    header("STEP 4 — CONCERT ENDS: the exodus surge")
    # Jump to just after the event ends, whatever EVENT_END_MINUTES is
    # currently set to — computed dynamically so this stays correct if
    # the schedule above changes, rather than a hardcoded minute count
    # calibrated to one specific start/end time.
    minutes_to_advance = max(5, (world.event_end_minutes + 5) - world.current_time_minutes)
    advance_time(world, minutes=minutes_to_advance)
    simulate_crowd_buildup(world)
    for node in world.transport_nodes.values():
        print(f"  {node.name:<26} load={node.load:>5}/{node.capacity:<5} "
              f"({node.congestion().value})")

    # ---------------------------------------------------------- STEP 5
    header("STEP 5 — DECENTRALISED DISTRIBUTION (simulated 50,000-attendee scale)")
    TOTAL_ATTENDEES = 50_000
    REAL_BATCH_SIZE = 10  # attendees who get a genuine LLM agent call in this demo
    real_batch = generate_population(REAL_BATCH_SIZE)

    if HAVE_KEY:
        from .agent import run_agent_for_attendee
        for a in real_batch:
            run_agent_for_attendee(a, world, milestone="after")
            # crude assignment for the chart: least-congested node — good enough
            # for a demo; a production version would parse the recommendation.
            a.assigned_transport_node = min(world.transport_nodes.values(), key=lambda n: n.load).id
    else:
        print(f"[No Bedrock credentials — skipping the {REAL_BATCH_SIZE} real-agent calls, "
              "using the statistical model for all attendees below.]")

    remaining = TOTAL_ATTENDEES - REAL_BATCH_SIZE
    simulated_split = redistribute_simulated(remaining, world, avoid_node="stadium_mrt")
    real_split = aggregate_signals(real_batch)  # 0 counts if HAVE_KEY is False
    with_intervention = simulated_split + real_split
    if not HAVE_KEY:
        # fold the un-run batch into the statistical model so totals still add up
        with_intervention += redistribute_simulated(REAL_BATCH_SIZE, world, avoid_node="stadium_mrt")

    baseline = without_intervention_baseline(TOTAL_ATTENDEES, world, default_node="stadium_mrt")

    print("\nWITHOUT KallangFlow (everyone defaults to the nearest exit):")
    bar_chart(dict(baseline), total_label="baseline, no agents")

    print("\nWITH KallangFlow (agent-guided redistribution):")
    bar_chart(dict(with_intervention),
              total_label=f"{REAL_BATCH_SIZE} real agents + statistical model")

    peak_before = max(baseline.values())
    peak_after = max(with_intervention.values())
    reduction = (1 - peak_after / peak_before) * 100 if peak_before else 0
    print(f"\nPeak node concentration: {peak_before:,} -> {peak_after:,} "
          f"({reduction:.0f}% reduction) [SIMULATED]")

    # ---------------------------------------------------------- STEP 6
    header("STEP 6 — JOURNEY GUARDIAN")
    if HAVE_KEY:
        from .agent import run_agent_for_attendee
        run_agent_for_attendee(demo_attendee, world, milestone="after")
        run_agent_for_attendee(demo_attendee, world, milestone="home")
    if GUARDIAN_LOG:
        for line in GUARDIAN_LOG:
            print(" ", line)
    else:
        print("  [No guardian messages logged — run with AWS Bedrock credentials set.]")

    header("DEMO COMPLETE")


if __name__ == "__main__":
    run_demo()
